### ISSUE TITLE
Docker build failure on master

### ISSUE THREAD

**Issue by aprettyloner** [jpetrucciani/bandit-check#16]
Docker build step is failing in github actions.
- Last success: `Mon Jul 17 07:56:51 PDT 2023`
- First failure: `Mon Jul 17 10:11:30 PDT 2023`

<details><summary>Configuration</summary>

```yaml
      # Run Bandit Static code analysis
      - uses: jpetrucciani/bandit-check@master
        with:
          path: "dags-2.0/${{ matrix.dag.name }}.py dags-2.0/utils/${{ matrix.dag.name }}"
          bandit_flags: "--severity high"
```
</details>

<details><summary>Error Log</summary>

```bash
Build container for action use: '/home/runner/work/_actions/jpetrucciani/bandit-check/master/Dockerfile'.
  /usr/bin/docker build -t c9a4a5:77e415b46cd7485a9d7a476b0004[2](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:2)01c -f "/home/runner/work/_actions/jpetrucciani/bandit-check/master/Dockerfile" "/home/runner/work/_actions/jpetrucciani/bandit-check/master"
  Sending build context to Docker daemon  13.82kB
  
  Step 1/6 : FROM python:3.11.4-alpine
  3.11.4-alpine: Pulling from library/python
  31e352740f53: Already exists
  cfcc276e4459: Pulling fs layer
  78d6a2cf8d41: Pulling fs layer
  129922027d23: Pulling fs layer
  c15df0cb361b: Pulling fs layer
  c15df0cb361b: Waiting
  cfcc276e4459: Verifying Checksum
  cfcc276e4459: Download complete
  129922027d23: Verifying Checksum
  129922027d23: Download complete
  78d6a2cf8d41: Verifying Checksum
  78d6a2cf8d41: Download complete
  c15df0cb361b: Verifying Checksum
  c15df0cb361b: Download complete
  cfcc276e4459: Pull complete
  78d6a2cf8d41: Pull complete
  129922027d23: Pull complete
  c15df0cb361b: Pull complete
  Digest: sha256:25df32b602118dab046b58f0fe920e3301da0727b5b07430c8bcd4b139627fdc
  Status: Downloaded newer image for python:3.11.4-alpine
   ---> 9a2ccd0e4ef5
  Step 2/6 : LABEL "maintainer"="Jacobi Petrucciani <j@cobi.dev>"
   ---> Running in 9059af6bb39a
  Removing intermediate container 9059af6bb39a
   ---> ba1a17e65f89
  Step 3/6 : ADD requirements.txt /requirements.txt
   ---> a110b3838b8d
  Step 4/6 : ADD entrypoint.sh /entrypoint.sh
   ---> 53a263917921
  Step 5/6 : RUN apk add gcc musl-dev &&     pip install -r requirements.txt
   ---> Running in ae0035ec488e
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
  (1/12) Installing libgcc (12.2.1_git20220924-r10)
  (2/12) Installing libstdc++ (12.2.1_git20220924-r10)
  (3/12) Installing zstd-libs (1.5.5-r4)
  (4/12) Installing binutils (2.40-r7)
  (5/12) Installing libgomp (12.2.1_git20220924-r10)
  (6/12) Installing libatomic (12.2.1_git20220924-r10)
  (7/12) Installing gmp (6.2.1-r3)
  (8/12) Installing isl26 (0.26-r1)
  (9/12) Installing mpfr4 (4.2.0-r3)
  (10/12) Installing mpc1 (1.3.1-r1)
  (11/12) Installing gcc (12.2.1_git20220924-r10)
  (12/12) Installing musl-dev (1.2.4-r0)
  Executing busybox-1.36.1-r0.trigger
  OK: 159 MiB in 50 packages
  Collecting bandit==1.7.5 (from -r requirements.txt (line 1))
    Downloading bandit-1.7.5-py3-none-any.whl (123 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.3/123.3 kB 7.6 MB/s eta 0:00:00
  Collecting bandit_sarif_formatter==1.1.1 (from -r requirements.txt (line 2))
    Downloading bandit_sarif_formatter-1.1.1-py3-none-any.whl (8.5 kB)
  Collecting GitPython>=1.0.1 (from bandit==1.7.5->-r requirements.txt (line 1))
    Downloading GitPython-3.1.32-py3-none-any.whl (188 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.5/188.5 kB 36.3 MB/s eta 0:00:00
  Collecting PyYAML>=5.3.1 (from bandit==1.7.5->-r requirements.txt (line 1))
    Downloading PyYAML-6.0.tar.gz (124 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 31.5 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [54 lines of output]
        running egg_info
        writing lib/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 288, in <module>
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<string>", line 204, in get_source_files
          File "/tmp/pip-build-env-lc1rvgu3/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: 23.1.2 -> 23.2
  Notice:  To update, run: pip install --upgrade pip
  The command '/bin/sh -c apk add gcc musl-dev &&     pip install -r requirements.txt' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 1.384 seconds before retry.
  /usr/bin/docker build -t c9a4a5:77e415b46cd7485a9d7a476b0004201c -f "/home/runner/work/_actions/jpetrucciani/bandit-check/master/Dockerfile" "/home/runner/work/_actions/jpetrucciani/bandit-check/master"
  Sending build context to Docker daemon  1[3](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:3).82kB
  
  Step 1/6 : FROM python:3.11.4-alpine
   ---> 9a2ccd0e4ef5
  Step 2/6 : LABEL "maintainer"="Jacobi Petrucciani <j@cobi.dev>"
   ---> Using cache
   ---> ba1a17e65f89
  Step 3/6 : ADD requirements.txt /requirements.txt
   ---> Using cache
   ---> a110b3838b8d
  Step 4/6 : ADD entrypoint.sh /entrypoint.sh
   ---> Using cache
   ---> 53a263917921
  Step 5/6 : RUN apk add gcc musl-dev &&     pip install -r requirements.txt
   ---> Running in 88fb3df8af3e
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
  (1/12) Installing libgcc (12.2.1_git20220924-r10)
  (2/12) Installing libstdc++ (12.2.1_git20220924-r10)
  (3/12) Installing zstd-libs (1.5.5-r4)
  (4/12) Installing binutils (2.40-r7)
  (5/12) Installing libgomp (12.2.1_git20220924-r10)
  (6/12) Installing libatomic (12.2.1_git20220924-r10)
  (7/12) Installing gmp (6.2.1-r3)
  (8/12) Installing isl26 (0.26-r1)
  (9/12) Installing mpfr4 (4.2.0-r3)
  (10/12) Installing mpc1 (1.3.1-r1)
  (11/12) Installing gcc (12.2.1_git20220924-r10)
  (12/12) Installing musl-dev (1.2.4-r0)
  Executing busybox-1.36.1-r0.trigger
  OK: 159 MiB in 50 packages
  Collecting bandit==1.7.5 (from -r requirements.txt (line 1))
    Downloading bandit-1.7.5-py3-none-any.whl (123 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.3/123.3 kB 7.8 MB/s eta 0:00:00
  Collecting bandit_sarif_formatter==1.1.1 (from -r requirements.txt (line 2))
    Downloading bandit_sarif_formatter-1.1.1-py3-none-any.whl (8.5 kB)
  Collecting GitPython>=1.0.1 (from bandit==1.7.5->-r requirements.txt (line 1))
    Downloading GitPython-3.1.32-py3-none-any.whl (188 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.5/188.5 kB 35.7 MB/s eta 0:00:00
  Collecting PyYAML>=5.3.1 (from bandit==1.7.5->-r requirements.txt (line 1))
    Downloading PyYAML-6.0.tar.gz (124 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 32.6 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [54 lines of output]
        running egg_info
        writing lib/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 288, in <module>
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<string>", line 204, in get_source_files
          File "/tmp/pip-build-env-2t8w644n/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: 23.1.2 -> 23.2
  Notice:  To update, run: pip install --upgrade pip
  The command '/bin/sh -c apk add gcc musl-dev &&     pip install -r requirements.txt' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 6.139 seconds before retry.
  /usr/bin/docker build -t c9a4a5:77e415b46cd7485a9d7a476b0004201c -f "/home/runner/work/_actions/jpetrucciani/bandit-check/master/Dockerfile" "/home/runner/work/_actions/jpetrucciani/bandit-check/master"
  Sending build context to Docker daemon  13.82kB
  
  Step 1/6 : FROM python:3.11.[4](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:4)-alpine
   ---> 9a2ccd0e4ef[5](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:5)
  Step 2/[6](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:6) : LABEL "maintainer"="Jacobi Petrucciani <j@cobi.dev>"
   ---> Using cache
   ---> ba1a1[7](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:7)e65f[8](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:8)[9](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:9)
  Step 3/6 : ADD requirements.txt /requirements.txt
   ---> Using cache
   ---> a1[10](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:10)b3838b8d
  Step 4/6 : ADD entrypoint.sh /entrypoint.sh
   ---> Using cache
   ---> 53a263917921
  Step 5/6 : RUN apk add gcc musl-dev &&     pip install -r requirements.txt
   ---> Running in 089f76fcb0a6
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
  (1/12) Installing libgcc (12.2.1_git20220924-r10)
  (2/12) Installing libstdc++ (12.2.1_git20220924-r10)
  (3/12) Installing zstd-libs (1.5.5-r4)
  (4/12) Installing binutils (2.40-r7)
  (5/12) Installing libgomp (12.2.1_git20220924-r10)
  (6/12) Installing libatomic (12.2.1_git20220924-r10)
  (7/12) Installing gmp (6.2.1-r3)
  (8/12) Installing isl26 (0.26-r1)
  (9/12) Installing mpfr4 (4.2.0-r3)
  (10/12) Installing mpc1 (1.3.1-r1)
  ([11](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:11)/[12](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:12)) Installing gcc (12.2.1_git20220924-r10)
  (12/12) Installing musl-dev (1.2.4-r0)
  Executing busybox-1.36.1-r0.trigger
  OK: 159 MiB in 50 packages
  Collecting bandit==1.7.5 (from -r requirements.txt (line 1))
    Downloading bandit-1.7.5-py3-none-any.whl (123 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.3/123.3 kB 8.6 MB/s eta 0:00:00
  Collecting bandit_sarif_formatter==1.1.1 (from -r requirements.txt (line 2))
    Downloading bandit_sarif_formatter-1.1.1-py3-none-any.whl (8.5 kB)
  Collecting GitPython>=1.0.1 (from bandit==1.7.5->-r requirements.txt (line 1))
    Downloading GitPython-3.1.32-py3-none-any.whl (188 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.5/188.5 kB 39.7 MB/s eta 0:00:00
  Collecting PyYAML>=5.3.1 (from bandit==1.7.5->-r requirements.txt (line 1))
    Downloading PyYAML-6.0.tar.gz (124 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 25.6 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [54 lines of output]
        running egg_info
        writing lib/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 288, in <module>
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 3[14](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:14), in run
            self.find_sources()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<string>", line [20](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:20)4, in get_source_files
          File "/tmp/pip-build-env-75cmqhmq/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: [23](https://github.com/VirtaHealth/airflow/actions/runs/5578518454/jobs/10192946297#step:2:23).1.2 -> 23.2
  Notice:  To update, run: pip install --upgrade pip
```
</details>

**Comment by jpetrucciani** [comment]
Thanks for the heads-up!

I've pushed a change to master that swaps the base image to a debian base, and that appears to build + install deps correctly. Could you let me know if that works as expected in your repo?

**Comment by aprettyloner** [comment]
Yes, this is now fixed @jpetrucciani. Thank you!
